In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [15]:
dataset = pd.read_excel("/home/maverick/ods_proj/Credit_score.xls")
dataset

TARGET      ID  DerogCnt  CollectCnt  BanruptcyInd  InqCnt06  \
0          1     582         3           3             0         4   
1          1     662        15           9             0         3   
2          1     805         0           0             0         1   
3          1    1175         8           5             0         6   
4          1    1373         3           1             0         9   
...      ...     ...       ...         ...           ...       ...   
2995       0  126441         0           0             0         2   
2996       0  126448         0           0             0         0   
2997       0  126465         1           1             0         8   
2998       0  126487         4           4             0         2   
2999       0  126503         2           1             1         0   

      InqTimeLast  InqFinanceCnt24  TLTimeFirst  TLTimeLast  ...  TL50UtilCnt  \
0             0.0                5          117          27  ...          3.0   
1             1.0                3           14          14  ...          1.0   
2             5.0                1          354           7  ...          5.0   
3             1.0               10           16           4  ...          3.0   
4             0.0                8          130          52  ...          1.0   
...           ...              ...          ...         ...  ...          ...   
2995          0.0                2          199          10  ...          9.0   
2996          NaN                0          270           3  ...          5.0   
2997          0.0                5          234           4  ...          9.0   
2998          3.0                1          257           3  ...          3.0   
2999         18.0                0          254         119  ...          1.0   

      TLBalHCPct  TLSatPct  TLDel3060Cnt24  TLDel90Cnt24  TLDel60CntAll  \
0         0.9179    0.2083               2             3              7   
1         0.8000    0.0000               0             0              0   
2         0.3552    0.6538               0             1              1   
3         0.9127    0.2500               1             1              1   
4         1.2511    0.0000               0             1              4   
...          ...       ...             ...           ...            ...   
2995      0.7853    0.6923               0             0              0   
2996      0.5766    0.9286               0             0              0   
2997      0.8722    0.6071               0             0              0   
2998      1.0391    0.6000               0             1              2   
2999      0.3239    0.1667               0             2              4   

      TLOpenPct  TLBadDerogCnt  TLDel60Cnt24  TLOpen24Pct  
0        0.2083              4             4       0.0000  
1        1.0000             12             0       1.0000  
2        0.7308              1             1       0.5263  
3        0.7500              7             1       1.3333  
4        0.1429              3             1       0.0000  
...         ...            ...           ...          ...  
2995     0.6538              0             0       0.3529  
2996     0.8571              0             0       0.4167  
2997     0.4286              1             0       0.7500  
2998     0.6000              4             1       1.0000  
2999     0.5000              3             2       0.0000  

[3000 rows x 30 columns]

In [16]:
dataset.columns

Index(['TARGET', 'ID', 'DerogCnt', 'CollectCnt', 'BanruptcyInd', 'InqCnt06',
       'InqTimeLast', 'InqFinanceCnt24', 'TLTimeFirst', 'TLTimeLast',
       'TLCnt03', 'TLCnt12', 'TLCnt24', 'TLCnt', 'TLSum', 'TLMaxSum',
       'TLSatCnt', 'TLDel60Cnt', 'TLBadCnt24', 'TL75UtilCnt', 'TL50UtilCnt',
       'TLBalHCPct', 'TLSatPct', 'TLDel3060Cnt24', 'TLDel90Cnt24',
       'TLDel60CntAll', 'TLOpenPct', 'TLBadDerogCnt', 'TLDel60Cnt24',
       'TLOpen24Pct'],
      dtype='object')

In [17]:
dataset.head()

TARGET    ID  DerogCnt  CollectCnt  BanruptcyInd  InqCnt06  InqTimeLast  \
0       1   582         3           3             0         4          0.0   
1       1   662        15           9             0         3          1.0   
2       1   805         0           0             0         1          5.0   
3       1  1175         8           5             0         6          1.0   
4       1  1373         3           1             0         9          0.0   

   InqFinanceCnt24  TLTimeFirst  TLTimeLast  ...  TL50UtilCnt  TLBalHCPct  \
0                5          117          27  ...          3.0      0.9179   
1                3           14          14  ...          1.0      0.8000   
2                1          354           7  ...          5.0      0.3552   
3               10           16           4  ...          3.0      0.9127   
4                8          130          52  ...          1.0      1.2511   

   TLSatPct  TLDel3060Cnt24  TLDel90Cnt24  TLDel60CntAll  TLOpenPct  \
0    0.2083               2             3              7     0.2083   
1    0.0000               0             0              0     1.0000   
2    0.6538               0             1              1     0.7308   
3    0.2500               1             1              1     0.7500   
4    0.0000               0             1              4     0.1429   

   TLBadDerogCnt  TLDel60Cnt24  TLOpen24Pct  
0              4             4       0.0000  
1             12             0       1.0000  
2              1             1       0.5263  
3              7             1       1.3333  
4              3             1       0.0000  

[5 rows x 30 columns]

In [18]:
dataset.tail()

TARGET      ID  DerogCnt  CollectCnt  BanruptcyInd  InqCnt06  \
2995       0  126441         0           0             0         2   
2996       0  126448         0           0             0         0   
2997       0  126465         1           1             0         8   
2998       0  126487         4           4             0         2   
2999       0  126503         2           1             1         0   

      InqTimeLast  InqFinanceCnt24  TLTimeFirst  TLTimeLast  ...  TL50UtilCnt  \
2995          0.0                2          199          10  ...          9.0   
2996          NaN                0          270           3  ...          5.0   
2997          0.0                5          234           4  ...          9.0   
2998          3.0                1          257           3  ...          3.0   
2999         18.0                0          254         119  ...          1.0   

      TLBalHCPct  TLSatPct  TLDel3060Cnt24  TLDel90Cnt24  TLDel60CntAll  \
2995      0.7853    0.6923               0             0              0   
2996      0.5766    0.9286               0             0              0   
2997      0.8722    0.6071               0             0              0   
2998      1.0391    0.6000               0             1              2   
2999      0.3239    0.1667               0             2              4   

      TLOpenPct  TLBadDerogCnt  TLDel60Cnt24  TLOpen24Pct  
2995     0.6538              0             0       0.3529  
2996     0.8571              0             0       0.4167  
2997     0.4286              1             0       0.7500  
2998     0.6000              4             1       1.0000  
2999     0.5000              3             2       0.0000  

[5 rows x 30 columns]

In [19]:
dataset.describe

<bound method NDFrame.describe of       TARGET      ID  DerogCnt  CollectCnt  BanruptcyInd  InqCnt06  \
0          1     582         3           3             0         4   
1          1     662        15           9             0         3   
2          1     805         0           0             0         1   
3          1    1175         8           5             0         6   
4          1    1373         3           1             0         9   
...      ...     ...       ...         ...           ...       ...   
2995       0  126441         0           0             0         2   
2996       0  126448         0           0             0         0   
2997       0  126465         1           1             0         8   
2998       0  126487         4           4             0         2   
2999       0  126503         2           1             1         0   

      InqTimeLast  InqFinanceCnt24  TLTimeFirst  TLTimeLast  ...  TL50UtilCnt  \
0             0.0                5          

In [20]:
dataset.shape

(3000, 30)

In [21]:
dataset = dataset.drop('ID',axis=1)
dataset.shape

(3000, 29)

In [26]:
dataset.head()

TARGET  DerogCnt  CollectCnt  BanruptcyInd  InqCnt06  InqTimeLast  \
0       1         3           3             0         4          0.0   
1       1        15           9             0         3          1.0   
2       1         0           0             0         1          5.0   
3       1         8           5             0         6          1.0   
4       1         3           1             0         9          0.0   

   InqFinanceCnt24  TLTimeFirst  TLTimeLast  TLCnt03  ...  TL50UtilCnt  \
0                5          117          27        0  ...          3.0   
1                3           14          14        0  ...          1.0   
2                1          354           7        0  ...          5.0   
3               10           16           4        0  ...          3.0   
4                8          130          52        0  ...          1.0   

   TLBalHCPct  TLSatPct  TLDel3060Cnt24  TLDel90Cnt24  TLDel60CntAll  \
0      0.9179    0.2083               2             3              7   
1      0.8000    0.0000               0             0              0   
2      0.3552    0.6538               0             1              1   
3      0.9127    0.2500               1             1              1   
4      1.2511    0.0000               0             1              4   

   TLOpenPct  TLBadDerogCnt  TLDel60Cnt24  TLOpen24Pct  
0     0.2083              4             4       0.0000  
1     1.0000             12             0       1.0000  
2     0.7308              1             1       0.5263  
3     0.7500              7             1       1.3333  
4     0.1429              3             1       0.0000  

[5 rows x 29 columns]

In [22]:
dataset.isna().sum()

TARGET               0
DerogCnt             0
CollectCnt           0
BanruptcyInd         0
InqCnt06             0
InqTimeLast        188
InqFinanceCnt24      0
TLTimeFirst          0
TLTimeLast           0
TLCnt03              0
TLCnt12              0
TLCnt24              0
TLCnt                3
TLSum               40
TLMaxSum            40
TLSatCnt             4
TLDel60Cnt           0
TLBadCnt24           0
TL75UtilCnt         99
TL50UtilCnt         99
TLBalHCPct          41
TLSatPct             4
TLDel3060Cnt24       0
TLDel90Cnt24         0
TLDel60CntAll        0
TLOpenPct            3
TLBadDerogCnt        0
TLDel60Cnt24         0
TLOpen24Pct          3
dtype: int64

In [23]:
dataset = dataset.fillna(dataset.mean()) 

In [24]:
dataset.isna().sum()

TARGET             0
DerogCnt           0
CollectCnt         0
BanruptcyInd       0
InqCnt06           0
InqTimeLast        0
InqFinanceCnt24    0
TLTimeFirst        0
TLTimeLast         0
TLCnt03            0
TLCnt12            0
TLCnt24            0
TLCnt              0
TLSum              0
TLMaxSum           0
TLSatCnt           0
TLDel60Cnt         0
TLBadCnt24         0
TL75UtilCnt        0
TL50UtilCnt        0
TLBalHCPct         0
TLSatPct           0
TLDel3060Cnt24     0
TLDel90Cnt24       0
TLDel60CntAll      0
TLOpenPct          0
TLBadDerogCnt      0
TLDel60Cnt24       0
TLOpen24Pct        0
dtype: int64

In [12]:
dataset.dtypes

TARGET               int64
DerogCnt             int64
CollectCnt           int64
BanruptcyInd         int64
InqCnt06             int64
InqTimeLast        float64
InqFinanceCnt24      int64
TLTimeFirst          int64
TLTimeLast           int64
TLCnt03              int64
TLCnt12              int64
TLCnt24              int64
TLCnt              float64
TLSum               object
TLMaxSum            object
TLSatCnt           float64
TLDel60Cnt           int64
TLBadCnt24           int64
TL75UtilCnt        float64
TL50UtilCnt        float64
TLBalHCPct          object
TLSatPct            object
TLDel3060Cnt24       int64
TLDel90Cnt24         int64
TLDel60CntAll        int64
TLOpenPct           object
TLBadDerogCnt        int64
TLDel60Cnt24         int64
TLOpen24Pct         object
dtype: object

In [25]:
y = dataset.iloc[:,0].values
y

array([1, 1, 1, ..., 0, 0, 0])

In [28]:
X = dataset.iloc[:,1:29].values
X

array([[ 3.    ,  3.    ,  0.    , ...,  4.    ,  4.    ,  0.    ],
       [15.    ,  9.    ,  0.    , ..., 12.    ,  0.    ,  1.    ],
       [ 0.    ,  0.    ,  0.    , ...,  1.    ,  1.    ,  0.5263],
       ...,
       [ 1.    ,  1.    ,  0.    , ...,  1.    ,  0.    ,  0.75  ],
       [ 4.    ,  4.    ,  0.    , ...,  4.    ,  1.    ,  1.    ],
       [ 2.    ,  1.    ,  1.    , ...,  3.    ,  2.    ,  0.    ]])

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.3,random_state=0,stratify=y)

In [31]:
from sklearn.preprocessing import StandardScaler

In [34]:
X_train = StandardScaler().fit_transform(X_train)
X_test = StandardScaler().fit_transform(X_test)

In [35]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report ,confusion_matrix,accuracy_score

In [36]:
model = LogisticRegression()

In [37]:
model.fit(X_train,y_train)

LogisticRegression()

In [38]:
y_pred = model.predict(X_test)

In [39]:
print(confusion_matrix(y_test,y_pred))

[[724  26]
 [123  27]]


In [40]:
print(accuracy_score(y_test,y_pred))

0.8344444444444444


In [41]:
testing = model.predict_proba(X_test)
testing

array([[0.92077614, 0.07922386],
       [0.92140916, 0.07859084],
       [0.95825034, 0.04174966],
       ...,
       [0.86566854, 0.13433146],
       [0.93823009, 0.06176991],
       [0.89626145, 0.10373855]])

In [43]:
df_prediction_prob = pd.DataFrame(testing, columns = ['prob_0', 'prob_1'])
df_prediction_target = pd.DataFrame(model.predict(X_test), columns = ['predicted_TARGET'])
df_test_dataset = pd.DataFrame(y_test,columns= ['Actual Outcome'])

dfx=pd.concat([df_test_dataset, df_prediction_prob, df_prediction_target], axis=1)

In [44]:
dfx.head()

Actual Outcome    prob_0    prob_1  predicted_TARGET
0               0  0.920776  0.079224                 0
1               0  0.921409  0.078591                 0
2               0  0.958250  0.041750                 0
3               0  0.912101  0.087899                 0
4               0  0.970521  0.029479                 0